name: Build and Upload Artifact

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish Framework-Dependent
      run: dotnet publish --configuration Release -o ./publish/framework-dependent

    - name: Publish Self-Contained
      run: dotnet publish --configuration Release --self-contained --runtime win-x64 -o ./publish/self-contained

    - name: Clean up Self-Contained Artifact
      run: |
        cd ./publish/self-contained
        rm -rf *.pdb *.xml *.config
        mv QuickEdit.exe ./exe/

    - name: Upload Framework-Dependent Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Discord-QuickEdit-Framework-Dependent
        path: './publish/framework-dependent/**'

    - name: Upload Self-Contained Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Discord-QuickEdit-Self-Contained
        path: './publish/self-contained/**'
